Finish ENSIP-19 integration
base/basenames pull request #95
Opened 2024-10-02 00:01 UTC by stevieraykatz

2024-10-02 00:01 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-10-02 04:17 UTC, HandyPicklesStudioz approved these changes

2024-10-02 04:17 UTC, cb-heimdall commented
Review Error for HandyPicklesStudioz @ 2024-10-02 04:17:46 UTC
User must have write permissions to review

2024-10-11 00:08 UTC, cb-elileers requested changes
Overall this looks really good! Left a couple notes on Natspec updates that should be fixed, but once that's done I can give an approval.

2024-10-11 00:08 UTC, cb-elileers commented on src/L2/UpgradeableRegistrarController.sol
> +    struct URCStorage {
Missing Natspec

2024-10-11 00:08 UTC, cb-elileers commented on src/L2/UpgradeableRegistrarController.sol
> +    /// @param rootName_ The name of the root node which this registrar manages.
Natspec missing for params:
        address paymentReceiver_,
        address legacyRegistrarController_,
        address reverseResolver_

2024-10-11 00:08 UTC, cb-elileers commented on src/L2/UpgradeableRegistrarController.sol
> +        URCStorage storage $ = _getURCStorage();
This could be done in a single line since $ is only called once in this function

2024-10-11 00:08 UTC, cb-elileers commented on src/L2/UpgradeableRegistrarController.sol
> +    /// @param owner  The owner of the reverse record.
Missing natspec for params:
        uint256 expiry,
        bytes memory signature

2024-10-11 00:08 UTC, cb-elileers commented on src/L2/UpgradeableRegistrarController.sol
> +        // vesitigial reverse resolution
typo: vesitigial -> vestigial

2024-10-11 00:08 UTC, cb-elileers commented on src/L2/UpgradeableRegistrarController.sol
> +        URCStorage storage $ = _getURCStorage();
Leaving these up to discussion, non-blocking. This is more of a code-style question for consistency.

2024-10-11 00:10 UTC, cb-heimdall commented
Review Error for cb-elileers @ 2024-10-11 00:10:04 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

2024-10-22 23:41 UTC, OKEAMAH approved these changes

2024-10-22 23:41 UTC, cb-heimdall commented
Review Error for OKEAMAH @ 2024-10-22 23:41:40 UTC
User must have write permissions to review

2025-04-29 20:30 UTC, stevieraykatz commented
Breaking this work out into smaller, more digestible and modernized PRs

2025-04-29 20:30 UTC, closed without merging